dataset:
  type: tinyimg
  root: /home/zhiyuan/CIL-CN/datasets/
  batch_size: 32
model:
  type: selector
  backbone: ResNet18_full
  header_mode: small
  selector:
    header_mode: small
    pretrained:
  buffer:
    mode: ring
    size: 5120
    loss: derpp
    alpha: 0.1
    beta: 0.5
    batch_size: 32
  pretrained:
  pretrain_model: /home/zhiyuan/CIL-CN/saved_models/model_best.pth.tar
optim:
  type: SGD
  lr: 0.03
  weight_decay: 0
  epochs: 100
  drop:
ckpt:
  save_dir: /home/zhiyuan/CIL-CN/saved_models/
logger:
  root: /home/zhiyuan/CIL-CN/log/
  name: test2
params: